### ISSUE TITLE
Deeplinks for module pages

### ISSUE THREAD

**Issue by lejoe** [ginetta/skeleton-styleguide#31]
## Problem:
When we switch to a specific module on http://preview.ginetta.net/skeleton-styleguide/master
The state is not updated in the url.
Meaning when you copy paste the url or reload you don't come back to the same component

## Solution:
1. On each click in the sidebar (i.e. Dropdowns), update the url of the styleguide to: http://preview.ginetta.net/skeleton-styleguide/master/?page=dropdown.html

2. On load of the page, read the page parameter and switch to the corresponding module

**Comment by lucalanca** [comment]
For 1. we could use the History API
